logging:
  version: 1
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout
  formatters:
    simple:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  root:
    level: DEBUG
    handlers: [console]

input:
  # excel_file_path: 'data/input.xlsx'
  excel_directory: 'data/'  # Directory containing Excel files
  includes: []              # List of sheet names to include, parse all if empty
  excludes: []        # List of sheet names to exclude

output:
  directory: 'data/'        # Directory to save the JSON files

chunk:
  size: 1000